name: Update TRC Connection + Guest Hour Calendar

on:
  schedule:
    - cron: "44 2 * * *"   
  workflow_dispatch:       # lets you trigger manually if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python Calendar.py

      - name: Commit and push updated .ics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filtered_rockgym_events.ics
          git commit -m "Auto-update filtered_rockgym_events.ics [skip ci]" --allow-empty
          git push
